server:
  port: ${PORT:5000}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/video_saas}

jwt:
  secret: ${JWT_SECRET:supersecretkeythatisatleast32characterslongforhmacsha256}
  expiration: 31536000000 # 365 days

gemini:
  api:
    key: ${GEMINI_API_KEY:}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}
